class IndianStatesCities {
  static const Map<String, List<String>> data = {
    'Andhra Pradesh': [
      'Visakhapatnam',
      'Vijayawada',
      'Guntur',
      'Nellore',
      'Kurnool',
      'Kakinada',
      'Tirupati',
      'Rajahmundry',
      'Kadapa',
      'Anantapur',
      'Vizianagaram',
      'Eluru',
      'Ongole',
      'Nandyal',
      'Machilipatnam',
      'Adoni',
      'Tenali',
      'Chittoor',
      'Hindupur',
      'Proddatur',
      'Srikakulam',
      'Bhimavaram'
    ],
    'Arunachal Pradesh': [
      'Itanagar',
      'Naharlagun',
      'Pasighat',
      'Tawang',
      'Ziro',
      'Bomdila',
      'Along',
      'Changlang',
      'Tezu',
      'Khonsa',
      'Roing'
    ],
    'Assam': [
      'Guwahati',
      'Silchar',
      'Dibrugarh',
      'Jorhat',
      'Nagaon',
      'Tinsukia',
      'Tezpur',
      'Bongaigaon',
      'Karimganj',
      'Sivasagar',
      'Goalpara',
      'Barpeta',
      'North Lakhimpur',
      'Dhubri',
      'Diphu',
      'Golaghat'
    ],
    'Bihar': [
      'Patna',
      'Gaya',
      'Bhagalpur',
      'Muzaffarpur',
      'Purnia',
      'Darbhanga',
      'Bihar Sharif',
      'Arrah',
      'Begusarai',
      'Katihar',
      'Munger',
      'Chhapra',
      'Danapur',
      'Saharsa',
      'Sasaram',
      'Hajipur',
      'Dehri',
      'Siwan',
      'Motihari',
      'Bettiah',
      'Buxar'
    ],
    'Chhattisgarh': [
      'Raipur',
      'Bhilai',
      'Bilaspur',
      'Korba',
      'Rajnandgaon',
      'Jagdalpur',
      'Durg',
      'Raigarh',
      'Ambikapur',
      'Mahasamund',
      'Dhamtari',
      'Chirmiri'
    ],
    'Goa': [
      'Panaji',
      'Margao',
      'Vasco da Gama',
      'Mapusa',
      'Ponda',
      'Bicholim',
      'Curchorem',
      'Sanquelim',
      'Cuncolim',
      'Canacona'
    ],
    'Gujarat': [
      'Ahmedabad',
      'Surat',
      'Vadodara',
      'Rajkot',
      'Bhavnagar',
      'Jamnagar',
      'Junagadh',
      'Gandhinagar',
      'Anand',
      'Navsari',
      'Morbi',
      'Nadiad',
      'Surendranagar',
      'Bharuch',
      'Mehsana',
      'Bhuj',
      'Porbandar',
      'Palanpur',
      'Valsad',
      'Vapi',
      'Godhra',
      'Patan',
      'Veraval'
    ],
    'Haryana': [
      'Gurugram',
      'Faridabad',
      'Panipat',
      'Ambala',
      'Yamunanagar',
      'Rohtak',
      'Hisar',
      'Karnal',
      'Sonipat',
      'Panchkula',
      'Bhiwani',
      'Sirsa',
      'Bahadurgarh',
      'Jind',
      'Thanesar',
      'Kaithal',
      'Rewari',
      'Palwal',
      'Kurukshetra',
      'Fatehabad'
    ],
    'Himachal Pradesh': [
      'Shimla',
      'Dharamshala',
      'Mandi',
      'Solan',
      'Kullu',
      'Manali',
      'Hamirpur',
      'Una',
      'Bilaspur',
      'Chamba',
      'Nahan',
      'Palampur',
      'Kasauli'
    ],
    'Jharkhand': [
      'Ranchi',
      'Jamshedpur',
      'Dhanbad',
      'Bokaro',
      'Deoghar',
      'Hazaribagh',
      'Giridih',
      'Ramgarh',
      'Medininagar',
      'Chirkunda',
      'Phusro',
      'Dumka'
    ],
    'Karnataka': [
      'Bengaluru',
      'Mysuru',
      'Hubballi-Dharwad',
      'Mangaluru',
      'Belagavi',
      'Davangere',
      'Ballari',
      'Vijayapura',
      'Shivamogga',
      'Tumakuru',
      'Raichur',
      'Bidar',
      'Hospet',
      'Gadag-Betageri',
      'Udupi',
      'Bagalkot',
      'Chitradurga',
      'Kolar',
      'Mandya',
      'Hassan',
      'Gulbarga'
    ],
    'Kerala': [
      'Thiruvananthapuram',
      'Kochi',
      'Kozhikode',
      'Kollam',
      'Thrissur',
      'Kannur',
      'Alappuzha',
      'Palakkad',
      'Kottayam',
      'Malappuram',
      'Kasaragod',
      'Pathanamthitta',
      'Idukki',
      'Wayanad',
      'Ernakulam'
    ],
    'Madhya Pradesh': [
      'Bhopal',
      'Indore',
      'Gwalior',
      'Jabalpur',
      'Ujjain',
      'Sagar',
      'Dewas',
      'Satna',
      'Ratlam',
      'Rewa',
      'Murwara',
      'Singrauli',
      'Burhanpur',
      'Khandwa',
      'Bhind',
      'Chhindwara',
      'Guna',
      'Shivpuri',
      'Vidisha',
      'Chhatarpur',
      'Damoh',
      'Mandsaur',
      'Neemuch'
    ],
    'Maharashtra': [
      'Mumbai',
      'Pune',
      'Nagpur',
      'Thane',
      'Pimpri-Chinchwad',
      'Nashik',
      'Kalyan-Dombivli',
      'Vasai-Virar',
      'Aurangabad',
      'Navi Mumbai',
      'Solapur',
      'Mira-Bhayandar',
      'Bhiwandi',
      'Amravati',
      'Nanded',
      'Kolhapur',
      'Akola',
      'Ulhasnagar',
      'Sangli-Miraj-Kupwad',
      'Malegaon',
      'Jalgaon',
      'Latur',
      'Dhule',
      'Ahmednagar',
      'Chandrapur',
      'Parbhani',
      'Ichalkaranji',
      'Jalna',
      'Ambarnath',
      'Bhusawal',
      'Ratnagiri',
      'Satara',
      'Panvel',
      'Beed',
      'Yavatmal',
      'Wardha',
      'Osmanabad'
    ],
    'Manipur': [
      'Imphal',
      'Churachandpur',
      'Thoubal',
      'Bishnupur',
      'Kakching',
      'Ukhrul'
    ],
    'Meghalaya': [
      'Shillong',
      'Tura',
      'Jowai',
      'Nongstoin',
      'Baghmara',
      'Williamnagar'
    ],
    'Mizoram': [
      'Aizawl',
      'Lunglei',
      'Saiha',
      'Champhai',
      'Kolasib',
      'Serchhip'
    ],
    'Nagaland': [
      'Kohima',
      'Dimapur',
      'Mokokchung',
      'Tuensang',
      'Wokha',
      'Zunheboto'
    ],
    'Odisha': [
      'Bhubaneswar',
      'Cuttack',
      'Rourkela',
      'Berhampur',
      'Sambalpur',
      'Puri',
      'Balasore',
      'Baripada',
      'Bhadrak',
      'Jharsuguda',
      'Jeypore',
      'Balangir',
      'Rayagada'
    ],
    'Punjab': [
      'Ludhiana',
      'Amritsar',
      'Jalandhar',
      'Patiala',
      'Bathinda',
      'Mohali',
      'Hoshiarpur',
      'Pathankot',
      'Moga',
      'Firozpur',
      'Batala',
      'Rajpura',
      'Kapurthala',
      'Sangrur',
      'Barnala',
      'Muktsar',
      'Fazilka'
    ],
    'Rajasthan': [
      'Jaipur',
      'Jodhpur',
      'Kota',
      'Bikaner',
      'Ajmer',
      'Udaipur',
      'Bhilwara',
      'Alwar',
      'Bharatpur',
      'Sikar',
      'Pali',
      'Sri Ganganagar',
      'Chittorgarh',
      'Jhunjhunu',
      'Churu',
      'Beawar',
      'Tonk',
      'Hanumangarh',
      'Dholpur',
      'Sawai Madhopur',
      'Nagaur',
      'Barmer',
      'Jaisalmer',
      'Banswara',
      'Dausa',
      'Rajsamand',
      'Sirohi'
    ],
    'Sikkim': ['Gangtok', 'Namchi', 'Geyzing', 'Mangan', 'Rangpo', 'Jorethang'],
    'Tamil Nadu': [
      'Chennai',
      'Coimbatore',
      'Madurai',
      'Tiruchirappalli',
      'Salem',
      'Tiruppur',
      'Erode',
      'Vellore',
      'Tirunelveli',
      'Thanjavur',
      'Thoothukudi',
      'Nagercoil',
      'Dindigul',
      'Kanchipuram',
      'Karur',
      'Cuddalore',
      'Kumbakonam',
      'Tiruvannamalai',
      'Rajapalayam',
      'Namakkal',
      'Sivakasi',
      'Hosur',
      'Ambur'
    ],
    'Telangana': [
      'Hyderabad',
      'Warangal',
      'Nizamabad',
      'Karimnagar',
      'Ramagundam',
      'Khammam',
      'Mahbubnagar',
      'Nalgonda',
      'Adilabad',
      'Suryapet',
      'Miryalaguda',
      'Siddipet'
    ],
    'Tripura': [
      'Agartala',
      'Udaipur',
      'Dharmanagar',
      'Kailashahar',
      'Belonia',
      'Khowai'
    ],
    'Uttar Pradesh': [
      'Lucknow',
      'Kanpur',
      'Ghaziabad',
      'Agra',
      'Meerut',
      'Varanasi',
      'Prayagraj',
      'Bareilly',
      'Aligarh',
      'Moradabad',
      'Saharanpur',
      'Gorakhpur',
      'Noida',
      'Firozabad',
      'Jhansi',
      'Muzaffarnagar',
      'Mathura',
      'Badaun',
      'Rampur',
      'Shahjahanpur',
      'Farrukhabad',
      'Ayodhya',
      'Jaunpur',
      'Ghazipur',
      'Gonda',
      'Mirzapur',
      'Bulandshahr',
      'Sambhal',
      'Amroha',
      'Hardoi',
      'Fatehpur',
      'Raebareli',
      'Orai',
      'Sitapur',
      'Etawah',
      'Mainpuri',
      'Deoria',
      'Basti',
      'Azamgarh'
    ],
    'Uttarakhand': [
      'Dehradun',
      'Haridwar',
      'Roorkee',
      'Haldwani',
      'Rudraprayag',
      'Rishikesh',
      'Kashipur',
      'Rudrapur',
      'Kotdwar',
      'Nainital',
      'Almora',
      'Pithoragarh',
      'Mussoorie'
    ],
    'West Bengal': [
      'Kolkata',
      'Howrah',
      'Asansol',
      'Siliguri',
      'Durgapur',
      'Bardhaman',
      'Malda',
      'Baharampur',
      'Habra',
      'Kharagpur',
      'Shantipur',
      'Ranaghat',
      'Darjeeling',
      'Jalpaiguri',
      'Krishnanagar',
      'Balurghat',
      'Basirhat',
      'Bankura',
      'Cooch Behar'
    ],
    // Union Territories
    'Andaman and Nicobar Islands': [
      'Port Blair',
      'Diglipur',
      'Rangat',
      'Car Nicobar'
    ],
    'Chandigarh': ['Chandigarh'],
    'Dadra and Nagar Haveli and Daman and Diu': ['Daman', 'Diu', 'Silvassa'],
    'Delhi': [
      'New Delhi',
      'North Delhi',
      'South Delhi',
      'East Delhi',
      'West Delhi',
      'Central Delhi',
      'North West Delhi',
      'South West Delhi',
      'North East Delhi',
      'South East Delhi',
      'Shahdara',
      'Dwarka',
      'Rohini',
      'Saket'
    ],
    'Jammu and Kashmir': [
      'Srinagar',
      'Jammu',
      'Anantnag',
      'Baramulla',
      'Kathua',
      'Udhampur',
      'Sopore',
      'Pulwama',
      'Kupwada',
      'Kulgam',
      'Rajouri',
      'Poonch'
    ],
    'Ladakh': ['Leh', 'Kargil'],
    'Lakshadweep': ['Kavaratti', 'Agatti', 'Amini', 'Minicoy'],
    'Puducherry': ['Puducherry', 'Karaikal', 'Yanam', 'Mahe'],
  };

  static List<String> get states => data.keys.toList()..sort();

  static List<String> getCities(String? state) {
    if (state == null || !data.containsKey(state)) return [];
    final cities = List<String>.from(data[state]!)..sort();
    return cities;
  }
}
